//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Research.DynamicDataDisplay.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Research.DynamicDataDisplay.Strings.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 is in «Auto Fit» mode by default. Using mouse with 的本地化字符串。
        /// </summary>
        internal static string About_1 {
            get {
                return ResourceManager.GetString("About_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouse drag 的本地化字符串。
        /// </summary>
        internal static string About_10 {
            get {
                return ResourceManager.GetString("About_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 — Select an area with current aspect ratio 的本地化字符串。
        /// </summary>
        internal static string About_11 {
            get {
                return ResourceManager.GetString("About_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 — Select an area to zoom in 的本地化字符串。
        /// </summary>
        internal static string About_12 {
            get {
                return ResourceManager.GetString("About_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 — Fit to view 的本地化字符串。
        /// </summary>
        internal static string About_13 {
            get {
                return ResourceManager.GetString("About_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 — Copy screenshot of chart to clipboard 的本地化字符串。
        /// </summary>
        internal static string About_14 {
            get {
                return ResourceManager.GetString("About_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 — Save screenshot of chart 的本地化字符串。
        /// </summary>
        internal static string About_15 {
            get {
                return ResourceManager.GetString("About_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 or 的本地化字符串。
        /// </summary>
        internal static string About_2 {
            get {
                return ResourceManager.GetString("About_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pressed down you can manually select an area to display. 的本地化字符串。
        /// </summary>
        internal static string About_3 {
            get {
                return ResourceManager.GetString("About_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouse wheel 的本地化字符串。
        /// </summary>
        internal static string About_4 {
            get {
                return ResourceManager.GetString("About_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 and 的本地化字符串。
        /// </summary>
        internal static string About_5 {
            get {
                return ResourceManager.GetString("About_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string About_6 {
            get {
                return ResourceManager.GetString("About_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 keys  —  Zoom in/Zoom out 的本地化字符串。
        /// </summary>
        internal static string About_7 {
            get {
                return ResourceManager.GetString("About_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouse drag 的本地化字符串。
        /// </summary>
        internal static string About_8 {
            get {
                return ResourceManager.GetString("About_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 — Pan the display area 的本地化字符串。
        /// </summary>
        internal static string About_9 {
            get {
                return ResourceManager.GetString("About_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://dynamicdatadisplay.codeplex.com 的本地化字符串。
        /// </summary>
        internal static string AboutSiteUrl {
            get {
                return ResourceManager.GetString("AboutSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About DynamicDataDisplay 的本地化字符串。
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy screenshot 的本地化字符串。
        /// </summary>
        internal static string ContextMenuCopyScreenshot {
            get {
                return ResourceManager.GetString("ContextMenuCopyScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy screenshot of charts to clipboard 的本地化字符串。
        /// </summary>
        internal static string ContextMenuCopyScreenshotTooltip {
            get {
                return ResourceManager.GetString("ContextMenuCopyScreenshotTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit to view 的本地化字符串。
        /// </summary>
        internal static string ContextMenuFitToView {
            get {
                return ResourceManager.GetString("ContextMenuFitToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make visible area fit to display entire contents 的本地化字符串。
        /// </summary>
        internal static string ContextMenuFitToViewTooltip {
            get {
                return ResourceManager.GetString("ContextMenuFitToViewTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick help 的本地化字符串。
        /// </summary>
        internal static string ContextMenuQuickHelp {
            get {
                return ResourceManager.GetString("ContextMenuQuickHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show brief instructions 的本地化字符串。
        /// </summary>
        internal static string ContextMenuQuickHelpTooltip {
            get {
                return ResourceManager.GetString("ContextMenuQuickHelpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report feedback 的本地化字符串。
        /// </summary>
        internal static string ContextMenuReportFeedback {
            get {
                return ResourceManager.GetString("ContextMenuReportFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create an e-mail message to report feedback or submit a bug 的本地化字符串。
        /// </summary>
        internal static string ContextMenuReportFeedbackTooltip {
            get {
                return ResourceManager.GetString("ContextMenuReportFeedbackTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save screenshot 的本地化字符串。
        /// </summary>
        internal static string ContextMenuSaveScreenshot {
            get {
                return ResourceManager.GetString("ContextMenuSaveScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specify name of image file to save screenshot to 的本地化字符串。
        /// </summary>
        internal static string ContextMenuSaveScreenshotTooltip {
            get {
                return ResourceManager.GetString("ContextMenuSaveScreenshotTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 d3@mslab.cs.msu.su 的本地化字符串。
        /// </summary>
        internal static string SendFeedbackEmail {
            get {
                return ResourceManager.GetString("SendFeedbackEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seems that there is no a mailto: handler installed.\nJust send an email to 的本地化字符串。
        /// </summary>
        internal static string SendFeedbackError {
            get {
                return ResourceManager.GetString("SendFeedbackError", resourceCulture);
            }
        }
    }
}
